spring.config.activate.on-profile: local

management:
  health:
    mail:
      enabled: false
spring:
  r2dbc:
    url: r2dbc:h2:file://localhost/~/areyouhere
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
    username: sa
    password:
  liquibase:
    change-log: liquibase/database_changelog.yaml
    url: jdbc:h2:file:~/areyouhere
    user: sa
    password:
    driver-class-name: org.h2.Driver
    enabled: true
    drop-first: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: null
    port: 1
    username: null
    password: null
    from: null
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: https://localhost:8080/api/login/oauth2/code/google
logging:
  level:
    root: info

cors:
  allowed-origins: http://localhost:5173

environment: local

cookie:
  encode: TEMP
