spring:
  application:
    name: areyouhere_webflux
  profiles:
    active: local
  config:
    import:
      - application-local.yaml
      - application-dev.yaml
      - application-release.yaml
server:
  port: 8080
  servlet:
    session:
      timeout: 60m

